### ISSUE TITLE
tootal page after where clause

### ISSUE THREAD

**Issue by deepaksp** [bhoriuchi/bookshelf-pagemaker#1]
first of all great job !!

```
        pagemaker(Model.QuoteTag).forge()
            .query(function(qb) {
                qb.where('tag_id_id', 'LIKE', result.get('id'));
            })
            .paginate({
                request: req
            })
            .end()
            .then(function (data) {
                res.json(data);
            });
```

result of this query is not giving filted total pages I mean
if I have total 10000 data and 100 data belongs to x,
and when I am searching for x it showing total 10000 not 100 (suppose limit is 1)

here is the orignal result 

{
  "previous": "URLpage=101",
  "current": "URLpage=102",
  "next": "URLpage=103",
  "limit": 40,
  "pagesTotal": 2877,
  "pagesFiltered": 2877,
  "resources": [
    // null bcz totalPage is 105 but showing 2877 !!
   // 2877 is actual totalPage without where clause 
  ]
}

**Comment by bhoriuchi** [comment]
I'll look into this. I ported all the code over from another project and expected there would be some bugs.

**Comment by bhoriuchi** [comment]
try my latest commit and let me know if that resolved your issue. it looks like i had code trying to get the results count after i already had the results and it was always getting a count for all rows. i removed it and set a property after the initial request.

**Comment by deepaksp** [comment]
pagesFiltered is now default to 1 not changing

pagesTotal still showing all records

and this time I unable to go to next page throwing 404 error

//output

  "previous": null,
  "current": "page=1",
  "next": null,
  "limit": 10,
  "pagesTotal": 11505,
  "pagesFiltered": 1,
  "resources":

**Comment by bhoriuchi** [comment]
can you try with 

```
        pagemaker(Model.QuoteTag).forge()
            .query(function(qb) {
                qb.where('tag_id_id', 'LIKE', '%' + result.get('id') + '%');
            })
            .paginate({
                request: req
            })
            .end()
            .then(function (data) {
                res.json(data);
            });
```

I'm assuming that result.get('id') returns a string? in which case your original query would return no results and a single page.

**Comment by deepaksp** [comment]
this is full code

```
new Model.Tag({'name': req.params.tags})
    .fetch()
    .then(function (result) {

        pagemaker(Model.QuoteTag).forge()
            .query(function(qb) {
                qb.where('tag_id_id', '=', result.get('id'));
            })
            .paginate({
                request: req
                //withRelated: ['getAuthor', 'getAuthorWiki'],
            })
            .end()
            .then(function (data) {
                res.json(data);
            });
    });
```

**Comment by bhoriuchi** [comment]
OK, i think i have resolved the issue now. The code i took out i actually shouldn't have. In short, the query builder was getting overwritten by the filtered count query before the filtered results query which caused the results query to be incorrect. 

the fix was to use an undocumented clone() method on the query builder before querying the filtered results. this captures the query you have created up until the pagination function as a new query builder instance. 

then using the cloned query builder, get the filtered count so that 2 separate query builder instances are being used in the operation. one for count, and one for filtered, limited, offset results

let me know if its working for you. i have attempted to copy your example in the example file v1-test.js in the getMovies function.

**Comment by deepaksp** [comment]
ok I understood but I have not used clone much so I have to check.
One personal suggestion
I really liked the old way of generating url for next and preivous pages
this one is little tricky bcz in old version we can specify req : req.params or req.query
I personally like req.query and this version uses req.params by default

**Comment by deepaksp** [comment]
working :100:   :+1:

**Comment by bhoriuchi** [comment]
you dont need to use clone in your code. i have added it to the project. i have also added transaction support and a `useQuery=true` option to the paginate function to use req.query instead of req.params. see the api doc in the wiki for details.

**Comment by deepaksp** [comment]
@bhoriuchi great job man :+1:
