### ISSUE TITLE
Change currentPage path/uri

### ISSUE THREAD

**Issue by harrythree** [bhoriuchi/bookshelf-pagemaker#3]
How would I set the path for the currentPage/next/previous? By default it looks like it pulls the tableName if schema._path.path is not set, but I could not find in the code where that could be set.

**Comment by bhoriuchi** [comment]
is this what you mean?

https://github.com/bhoriuchi/bookshelf-pagemaker/wiki/API-1.0#pmhref-uri-

**Comment by harrythree** [comment]
``` javascript
pm(Series).forge()
.query(function(qb) {
  qb.where('name', 'LIKE', '%'+req.query.name+'%');
})
.href('/series')
.paginate({
  request: req
})
.end()
.then(function(results) {
  res.status(200).json(results);
})
.catch(next);
```

I tried adding that and it did not have any effect. It looks like this will add the "base" for the url but not the path. My problem is that my current/next/previous urls are all returned with this format:

 http://localhost:8080/gcd_series?limit=10&page=2

 and I want them to look like this:

http://localhost:8080/series?limit=10&page=2

gcd_series is the table name but my endpoint is /series.

It looks like the code sets that as the default here:

https://github.com/bhoriuchi/bookshelf-pagemaker/blob/master/lib/core/utils/pagination.js#L95

So that's what made me think I could set "schema._path.path" somewhere in the configurations.

**Comment by bhoriuchi** [comment]
i see. I actually pulled the current pagination code for my bookshelf-factory project so there are still some things to clean up. in bookshelf-factory you specify schema objects and one of options i have is to specify a path for just what you are trying to accomplish.

i will need to add this functionality into pagemaker. would it be adequate for you to have an option in the paginate  options hash to override the table name with a custom path? see updated example below

```
pm(Series).forge()
.query(function(qb) {
  qb.where('name', 'LIKE', '%'+req.query.name+'%');
})
.paginate({
  request: req,
  path: '/series'
})
.end()
.then(function(results) {
  res.status(200).json(results);
})
.catch(next);
```

**Comment by bhoriuchi** [comment]
I have added the previously mentioned option and published version 1.0.5 to npm. Please let me know if this gives you the functionality you are looking for and i will close out the issue.

**Comment by harrythree** [comment]
Works great! Thanks! 

Love the module, this is the second project I've used it with.

**Comment by bhoriuchi** [comment]
That's great!
