### ISSUE TITLE
Ordering related columns not working [Express][Postgres]

### ISSUE THREAD

**Issue by alimustofa** [bhoriuchi/bookshelf-pagemaker#4]
Hi bhoriuchi, please help me

Controller: 

```
pm(PartCondition, 'datatables').forge()
            .paginate({
                request: req,
                withRelated: ['part'],
            })
            .end()
            .then(function(results) {
                res.send(results);
            });
```

View: 

```
$("#data-partConditions").DataTable({
        "processing": true,
        "serverSide": true,
        "ajax": {
            url: "/conditions/data",
            type: 'GET'
        },
        "columns": [
                { "data": "part.name",
                   orderable: true },
                { "data": "description",
                   orderable: true },
              ]
    })
```

![image](https://cloud.githubusercontent.com/assets/5575745/14876186/81deef38-0d3c-11e6-9927-7e3a38786460.png)

When I clicked Description column, sorting was worked, but when I clicked Part Column not worked.
Is it possible to sorting related column with bookshelf-pagemaker?

Thanks

**Comment by bhoriuchi** [comment]
I will look into this, but my initial thoughts are that I may be able to use virtuals to do this or that you will take a performance hit since server side ordering is done per table so pagemaker would need to get all results and sort them in node before sending the results

**Comment by RodolfoSilva** [comment]
Comment moved to #6

**Comment by bhoriuchi** [comment]
@RodolfoSilva please open this in a separate issue as it is not the same issue @alimustofa is trying to accomplish.Also please provide your table schema in that issue

Thanks!
