### ISSUE TITLE
witRelated not working

### ISSUE THREAD

**Issue by RodolfoSilva** [bhoriuchi/bookshelf-pagemaker#6]
The `withRelated` not working for me... I have this code.

``` javascript
var Doctor = ORM.Model.extend({
  tableName: 'doctors',
});

var Pacient = ORM.Model.extend({
  tableName:  'pacients',
  hasTimestamps: true,
  doctor: function() {
    return this.belongsTo(Doctor, 'doctor_id');
  } 
});
```

if I use this:

``` javascript
new Pacient()
  .fetchAll({ withRelated: ['doctor'] })
  .then(function (pacientes) {
    // Result
    [
      {
        id: 1,
        name: 'Paciente name',
        doctor_id: 3,
        doctor: {
          id: 3,
          name: 'Doctor name',
        }
      }
    ]
  });
```

But if I use pagination my result is this: 

``` javascript
pm(Pacient)
  .forge()
  .paginate({ withRelated: ['doctor'] })
  .end()
  .then(function (pacientes) {
    // Result
    [
      {
        id: 1,
        name: 'Paciente name',
        doctor_id: 3
      }
    ]
  });
```

sorry for my bad english...

![der](https://cloud.githubusercontent.com/assets/1703020/14890077/9d70859a-0d37-11e6-88ef-15051cdd8015.png)

**Comment by bhoriuchi** [comment]
please try adding the .end() method before your then

```
pm(Pacient)
  .forge()
  .paginate({ withRelated: ['doctor'] })
  .end()
  .then(function (pacientes) {
    // Result
    [
      {
        id: 1,
        name: 'Paciente name',
        doctor_id: 3
      }
    ]
  });
```

**Comment by RodolfoSilva** [comment]
Sorry, I had already put ... But I forgot to explain in my comment...

**Comment by bhoriuchi** [comment]
i have found the issue. All testing done has been with express and restify. Since you are using neither, pagemaker doesnt currently have a case to handle your pagination. I will add this (because it should have already been there) and publish a new version. Thanks for finding this!

**Comment by bhoriuchi** [comment]
Actually, going over the code (its been a while) you just need to provide a request object. it can be an empty object. I will update the wiki and default the object to {} but you should be able to get it working now with the following

```
pm(Pacient)
  .forge()
  .paginate({ withRelated: ['doctor'], request: {} })
  .end()
  .then(function (pacientes) {
    // Result
    [
      {
        id: 1,
        name: 'Paciente name',
        doctor_id: 3
      }
    ]
  });
```

**Comment by bhoriuchi** [comment]
version 1.0.6 published to npm with fix. let me know if you still have an issue.

**Comment by RodolfoSilva** [comment]
Thanks... :)
