### ISSUE TITLE
Build unit tests

### ISSUE THREAD

**Issue by RodolfoSilva** [bhoriuchi/bookshelf-pagemaker#8]
We need make unit tests for this project.

What do you think?

**Comment by bhoriuchi** [comment]
i think that would be good, but i have no experience with developing tests. i can add you to the project if you would like to work on them.

**Comment by RodolfoSilva** [comment]
Yes, i accept. :+1:

**Comment by bhoriuchi** [comment]
you have been added.

**Comment by RodolfoSilva** [comment]
Nice :+1:
