### ISSUE TITLE
bookshelf-pagemaker set Limit not function [Express][postgres]

### ISSUE THREAD

**Issue by hendarSu** [bhoriuchi/bookshelf-pagemaker#9]
please help me!

controller :
![screenshot from 2017-05-15 17-55-51](https://cloud.githubusercontent.com/assets/7671353/26054713/c5cf9782-3997-11e7-83ca-73f726a5b1ac.png)

result :
![screenshot from 2017-05-15 17-57-52](https://cloud.githubusercontent.com/assets/7671353/26054773/1099b14e-3998-11e7-9f28-f5af430bc3b8.png)

The wrong setting in which part? :(

**Comment by bhoriuchi** [comment]
Try chaining your query method before paginate. Also there is an order method https://github.com/bhoriuchi/bookshelf-pagemaker/wiki/API-1.0#pmorder-order-

**Comment by hendarSu** [comment]
It works, thanks

**Comment by bhoriuchi** [comment]
Great!
